[2022-07-09 13:54:23.079] [exthost] [info] Extension host with pid 426 started
[2022-07-09 13:54:23.079] [exthost] [info] Skipping acquiring lock for /home/intcesar/.config/Code/User/workspaceStorage/789bbeec6e725d257406688d4d200746.
[2022-07-09 13:54:23.676] [exthost] [info] ExtensionService#_doActivateExtension mechatroner.rainbow-csv, startup: false, activationEvent: 'onLanguage:plaintext'
[2022-07-09 13:54:23.707] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python'
[2022-07-09 13:54:23.904] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
[2022-07-09 13:54:24.282] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-07-09 13:54:24.374] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-07-09 13:54:24.390] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2022-07-09 13:54:24.415] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-07-09 13:54:25.692] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-07-09 13:54:25.790] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-07-09 13:54:26.389] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2022-07-09 13:54:26.473] [exthost] [info] Eager extensions activated
[2022-07-09 13:54:26.631] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-07-09 13:54:26.653] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-07-09 13:54:26.664] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-07-09 16:46:38.748] [exthost] [error] [ms-python.python] provider FAILED
[2022-07-09 16:46:38.749] [exthost] [error] Error: ValueError: `column` parameter (5) is not in a valid range (0-4) for line 26 ('    \n').
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140123
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140417
	at Immediate.<anonymous> (/home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140780)
	at processImmediate (node:internal/timers:464:21)
[2022-07-12 23:10:39.291] [exthost] [error] [ms-python.python] provider FAILED
[2022-07-12 23:10:39.300] [exthost] [error] Error: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 3 ('\n').
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140123
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140417
	at Immediate.<anonymous> (/home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140780)
	at processImmediate (node:internal/timers:464:21)
[2022-07-12 23:11:40.543] [exthost] [error] [ms-python.python] provider FAILED
[2022-07-12 23:11:40.544] [exthost] [error] Error: DisposableStore is missing...
	at X._convertCompletionItem (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:109928)
	at X.resolveCompletionItem (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:109706)
[2022-07-13 08:58:23.543] [exthost] [error] [ms-python.python] provider FAILED
[2022-07-13 08:58:23.547] [exthost] [error] Error: UnboundLocalError: local variable 'start_index' referenced before assignment
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140123
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140417
	at Immediate.<anonymous> (/home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140780)
	at processImmediate (node:internal/timers:464:21)
[2022-07-13 09:02:47.037] [exthost] [error] [ms-python.python] provider FAILED
[2022-07-13 09:02:47.043] [exthost] [error] Error: UnboundLocalError: local variable 'end_index' referenced before assignment
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140123
	at /home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140417
	at Immediate.<anonymous> (/home/intcesar/.vscode/extensions/ms-python.python-2022.4.1/out/client/extension.js:47:140780)
	at processImmediate (node:internal/timers:464:21)
